DEVX-5926 and DEVX-5937 Add dvr and lowlatency options for HLS Broadcasts
opentok/OpenTok-Ruby-SDK pull request #243
Opened 2022-04-20 10:58 UTC by superchilled

## Description

- Adds `dvr` and `lowlatency` options for `hls` Broadcast objects
- Updates code comments for usage of these options
- Adds a check that both are not set to `true` simultaneously

## Motivation and Context

It implements a feature in the SDK which has already been added to the API.

## How Has This Been Tested?

Added a test for the conditional check.

## Example Output or Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-05-04 16:13 UTC, jeffswartz requested changes
Please rev the version number (to 4.4.0) in the lib/opentok/version.rb file.

2022-05-05 11:43 UTC, superchilled commented
> Please rev the version number (to 4.4.0) in the lib/opentok/version.rb file.

👍🏾 Done in [this commit](https://github.com/opentok/OpenTok-Ruby-SDK/pull/243/commits/93013c416d3f48835121caf00dbe184fc93f1d8d)

2022-05-06 16:56 UTC, jeffswartz approved these changes

2022-05-06 16:58 UTC, jeffswartz approved these changes

2022-05-09 11:25 UTC, merged